spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lab_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: labuser
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver